eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
    metadata-map:
      VERSION: v1
  client:
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://register-server.pveruntimedev.svc.cluster.local:8000/eureka/}
    registryFetchIntervalSeconds: 10
mybatis:
  mapperLocations: classpath*:/mapper/*.xml
  configuration: # 数据库下划线转驼峰配置
    mapUnderscoreToCamelCase: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_service?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
#choerodon:
#  saga:
#    consumer:
#      enabled: true
#      thread-num: 2 # saga消息消费线程池大小
#      max-poll-size: 200 # 每次拉取消息最大数量
#      poll-interval-ms: 1000 # 拉取间隔，默认1000毫秒

